name: dackservice
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  http: ^0.13.4
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1
  flutter_lints: ^1.0.0
  flutter_keyboard_visibility: ^5.1.0
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.17.0
  flutter_svg: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/barcode.svg
    - assets/images/bg_image1.jpg
    - assets/images/bg_image2.jpg
    - assets/images/bg_image2.png
#    - assets/image/logo1.webp
#    - assets/image/biesse_start.png
#    - assets/image/biesse_start1.png